General:
  ListenAddress: 0.0.0.0
  ListenPort: 7050
  TLS:
    Enabled: true
    PrivateKey: /var/hyperledger/orderer/tls/server.key
    Certificate: /var/hyperledger/orderer/tls/server.crt
    RootCAs:
      - /var/hyperledger/orderer/tls/ca.crt
    ClientAuthRequired: false
    ClientRootCAs:
  Keepalive:
    ServerMinInterval: 60s
    ServerInterval: 7200s
    ServerTimeout: 20s
  MaxRecvMsgSize: 104857600
  MaxSendMsgSize: 104857600
  Cluster:
    ClientCertificate: /var/hyperledger/orderer/tls/server.crt
    ClientPrivateKey: /var/hyperledger/orderer/tls/server.key
    ListenPort:
    ListenAddress:
    ServerCertificate:
    ServerPrivateKey:
    RootCAs:
      - /var/hyperledger/orderer/tls/ca.crt
  BootstrapMethod: none
  LocalMSPDir: /var/hyperledger/orderer/msp
  LocalMSPID: OrdererMSP
  Profile:
    Enabled: false
    Address: 0.0.0.0:6060
  BCCSP:
    Default: SW
    SW:
      Hash: SHA2
      Security: 256
      FileKeyStore:
        KeyStore:
  Authentication:
    TimeWindow: 15m

FileLedger:
  Location: /var/hyperledger/production/orderer

Debug:
  BroadcastTraceDir:
  DeliverTraceDir:

Operations:
  ListenAddress: 0.0.0.0:9443
  TLS:
    Enabled: false
    Certificate:
    PrivateKey:
    ClientAuthRequired: false
    ClientRootCAs: []

Metrics:
  Provider: prometheus

Admin:
  ListenAddress: 0.0.0.0:7053
  TLS:
    Enabled: true
    Certificate: /var/hyperledger/orderer/tls/server.crt
    PrivateKey: /var/hyperledger/orderer/tls/server.key
    RootCAs:
      - /var/hyperledger/orderer/tls/ca.crt
    ClientAuthRequired: true
    ClientRootCAs:
      - /var/hyperledger/orderer/tls/ca.crt

ChannelParticipation:
  Enabled: true
  MaxRequestBodySize: 1 MB

Consensus:
  WALDir: /var/hyperledger/production/orderer/etcdraft/wal
  SnapDir: /var/hyperledger/production/orderer/etcdraft/snapshot
